import { Inter } from "next/font/google";
import "./globals.css";
import { ColorProvider } from "./context/ColorContext"; // ColorProviderをインポート
import Head from "next/head"; // Headをインポート

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kid's Compass",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* SVGファビコンの設定 */}
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>
      <body className={inter.className}>
        <ColorProvider>{children}</ColorProvider>
      </body>
    </html>
  );
}
